In [5]:
import requests
import re
import pandas as pd
import os
import csv
import statistics
import numpy as np

In [59]:
races = pd.read_csv('Cook-Ratings.csv')

In [86]:
races.tail()

     YEAR DISTRICT REPRESENTATIVE   PVI           CATEGORY
436  2010    PA-06    Jim Gerlach   D+4  LIKELY REPUBLICAN
437  2010    PA-15   Charlie Dent   D+2  LIKELY REPUBLICAN
438  2010    TN-06           Open  R+13  LIKELY REPUBLICAN
439  2010    TN-08           Open   R+6  LIKELY REPUBLICAN
440  2010    WA-08  Dave Reichert   D+3  LIKELY REPUBLICAN

In [61]:
len(races)

441

In [62]:
results = pd.read_csv('1976-2018-house.csv', encoding="ISO-8859-1")

In [63]:
df = results[results['year'] > 2009]

In [87]:
len(df)

7083

In [89]:
df.candidatevotes = df.candidatevotes.str.replace(",","")

In [67]:
df.candidatevotes = df.candidatevotes.astype(float)

In [68]:
df['district'] = df['district'].apply(lambda x: '{0:0>2}'.format(x))

/Users/elenacox/.pyenv/versions/3.7.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [90]:
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,DISTRICT
22553,2010,Alabama,AL,1,63,41,US House,01,gen,NaN,False,Jo Bonner,republican,False,total,129063.0,156281.0,False,20171005,AL-01
22554,2010,Alabama,AL,1,63,41,US House,01,gen,NaN,False,David Walter,constitution,False,total,26357.0,156281.0,False,20171005,AL-01
22555,2010,Alabama,AL,1,63,41,US House,01,gen,NaN,False,NaN,NaN,True,total,861.0,156281.0,False,20171005,AL-01
22556,2010,Alabama,AL,1,63,41,US House,02,gen,NaN,False,Bobby Bright,democrat,False,total,106865.0,219028.0,False,20171005,AL-02
22557,2010,Alabama,AL,1,63,41,US House,02,gen,NaN,False,NaN,NaN,True,total,518.0,219028.0,False,20171005,AL-02

In [71]:
df['DISTRICT'] = df.state_po + "-" + df.district

/Users/elenacox/.pyenv/versions/3.7.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [72]:
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,DISTRICT
22553,2010,Alabama,AL,1,63,41,US House,01,gen,NaN,False,Jo Bonner,republican,False,total,129063.0,156281.0,False,20171005,AL-01
22554,2010,Alabama,AL,1,63,41,US House,01,gen,NaN,False,David Walter,constitution,False,total,26357.0,156281.0,False,20171005,AL-01
22555,2010,Alabama,AL,1,63,41,US House,01,gen,NaN,False,NaN,NaN,True,total,861.0,156281.0,False,20171005,AL-01
22556,2010,Alabama,AL,1,63,41,US House,02,gen,NaN,False,Bobby Bright,democrat,False,total,106865.0,219028.0,False,20171005,AL-02
22557,2010,Alabama,AL,1,63,41,US House,02,gen,NaN,False,NaN,NaN,True,total,518.0,219028.0,False,20171005,AL-02

In [82]:
byrace = df.groupby(['DISTRICT', 'year', 'party'], sort=False)['candidatevotes'].max()

In [84]:
byrace.tail()

DISTRICT  year  party
WI-08     2018  democrat        119265.0
WY-00     2018  republican      127963.0
                democrat         59903.0
                libertarian       6918.0
                constitution      6070.0
Name: candidatevotes, dtype: float64

In [85]:
byrace.to_csv('byrace.csv')

/Users/elenacox/.pyenv/versions/3.7.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [91]:
byrace2 = pd.read_csv('byrace.csv')

In [102]:
byrace3 = byrace2.loc[byrace2.reset_index().groupby(['DISTRICT', 'YEAR'])['VOTES'].idxmax()]

In [103]:
len(races)

441

In [104]:
byrace3.head(50)

     DISTRICT  YEAR      WINNER     VOTES
12      AK-00  2010  republican  175384.0
1289    AK-00  2012  republican  185296.0
2506    AK-00  2014  republican  142572.0
3644    AK-00  2016  republican  155088.0
4817    AK-00  2018  republican  149779.0
0       AL-01  2010  republican  129063.0
1275    AL-01  2012  republican  196374.0
2494    AL-01  2014  republican  103758.0
3632    AL-01  2016  republican  208083.0
4804    AL-01  2018  republican  153228.0
3       AL-02  2010  republican  111645.0
1277    AL-02  2012  republican  180591.0
2496    AL-02  2014  republican  113103.0
3634    AL-02  2016  republican  134886.0
4805    AL-02  2018  republican  138879.0
4       AL-03  2010  republican  117736.0
1278    AL-03  2012  republican  175306.0
2499    AL-03  2014  republican  103558.0
3635    AL-03  2016  republican  192164.0
4807    AL-03  2018  republican  147770.0
6       AL-04  2010  republican  167714.0
1281    AL-04  2012  republican  199071.0
2500    AL-04  2014  republican  132831.0
3637    AL-04  2016  republican  235925.0
4809    AL-04  2018  republican  184255.0
8       AL-05  2010  republican  131109.0
1283    AL-05  2012  republican  189185.0
2502    AL-05  2014  republican  115338.0
3638    AL-05  2016  republican  205647.0
4811    AL-05  2018  republican  159063.0
9       AL-06  2010  republican  205288.0
1285    AL-06  2012  republican  219262.0
2504    AL-06  2014  republican  135945.0
3641    AL-06  2016  republican  245313.0
4813    AL-06  2018  republican  192542.0
10      AL-07  2010    democrat  136696.0
1287    AL-07  2012    democrat  232520.0
2505    AL-07  2014    democrat  133687.0
3642    AL-07  2016    democrat  229330.0
4815    AL-07  2018    democrat  185010.0
42      AR-01  2010  republican   93224.0
1320    AR-01  2012  republican  138800.0
2534    AR-01  2014  republican  124139.0
3667    AR-01  2016  republican  183866.0
4837    AR-01  2018  republican  138757.0
47      AR-02  2010  republican  122091.0
1322    AR-02  2012  republican  158175.0
2538    AR-02  2014  republican  123073.0
3668    AR-02  2016  republican  176472.0
4840    AR-02  2018  republican  132125.0

In [106]:
races2 = pd.merge(byrace3, races, on=['DISTRICT', 'YEAR'])

In [110]:
races2.head()

,DISTRICT,YEAR,WINNER,VOTES,REPRESENTATIVE,PVI,CATEGORY
0,AL-02,2010,republican,111645.0,Bobby Bright,R+16,TOSS-UP DEMOCRATIC
1,AL-05,2010,republican,131109.0,Open,R+12,LIKELY REPUBLICAN
2,AR-01,2010,republican,93224.0,Open,R+8,LEAN REPUBLICAN
3,AR-01,2012,republican,138800.0,Rick Crawford,R+7,LIKELY REPUBLICAN
4,AR-02,2010,republican,122091.0,Open,R+5,LIKELY REPUBLICAN

In [111]:
races2.to_csv('Cook_Compare.csv')

In [112]:
accuracy = pd.read_csv('Cook_Accuracy.csv')

In [113]:
accuracy.head()

  DISTRICT  YEAR      WINNER            CATEGORY ACCURACY
0    AL-02  2010  republican  TOSS-UP DEMOCRATIC        N
1    AL-05  2010  republican   LIKELY REPUBLICAN        Y
2    AR-01  2010  republican     LEAN REPUBLICAN        Y
3    AR-01  2012  republican   LIKELY REPUBLICAN        Y
4    AR-02  2010  republican   LIKELY REPUBLICAN        Y

In [116]:
accuracy2 = accuracy.groupby('YEAR')['ACCURACY'].value_counts()

In [117]:
accuracy2.to_csv('Cook_Accuracy_counts.csv')

/Users/elenacox/.pyenv/versions/3.7.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.